// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn-uS_QpXb574cGaGmEW28rkppTAmZ_mw',
    appId: '1:977841302259:web:f57cd8b76c61e40f566586',
    messagingSenderId: '977841302259',
    projectId: 'cinemon-edce3',
    authDomain: 'cinemon-edce3.firebaseapp.com',
    storageBucket: 'cinemon-edce3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmEJOTlz1eJ5YqwLxv8fth-6y3_VNNnE',
    appId: '1:977841302259:android:6f2f4ac911607a9d566586',
    messagingSenderId: '977841302259',
    projectId: 'cinemon-edce3',
    storageBucket: 'cinemon-edce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP2mOWhZSGUgejF0qBEBa1eowRDzjA0iM',
    appId: '1:977841302259:ios:0c44a22aaf7a802a566586',
    messagingSenderId: '977841302259',
    projectId: 'cinemon-edce3',
    storageBucket: 'cinemon-edce3.appspot.com',
    iosClientId: '977841302259-t4hlf4plmkd0b5mco75afq5v6eiqtq44.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP2mOWhZSGUgejF0qBEBa1eowRDzjA0iM',
    appId: '1:977841302259:ios:0c44a22aaf7a802a566586',
    messagingSenderId: '977841302259',
    projectId: 'cinemon-edce3',
    storageBucket: 'cinemon-edce3.appspot.com',
    iosClientId: '977841302259-t4hlf4plmkd0b5mco75afq5v6eiqtq44.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemon',
  );
}
